branches-template:
  - main: "{{ref-name}}-{{timestamp}}-{{run_number}}, {{ref-name}}-snapshot"
  - "feature/*": "{{ref-name}}-{{timestamp}}-{{run_number}}.{{dist-tag}}"
  - "release/*": "{{ref-name}}-{{timestamp}}-{{run_number}}.{{dist-tag}}"
  - "hotfix/*": "{{ref-name}}-{{timestamp}}-{{run_number}}"
  - "bugfix/*": "{{ref-name}}-{{timestamp}}-{{run_number}}"

distribution-tag:
  - main: "latest"
  - "release/*": "next"
  - "feature/*": "beta"
  - tag: "stable"

default-template: "{{ref-name}}-{{timestamp}}-{{run_number}}"
