branches-template:
  - main: "{{ref-name}}-{{timestamp}}-{{run-number}}, {{ref-name}}-snapshot"
  - "feature/*": "{{ref-name}}-{{timestamp}}-{{context.runNumber}}.{{dist-tag}}"
  - "release/*": "{{ref-name}}-{{timestamp}}-{{run-number}}.{{dist-tag}}"
  - "hotfix/*": "{{ref-name}}-{{timestamp}}-{{run-number}}"
  - "bugfix/*": "{{ref-name}}-{{timestamp}}-{{run-number}}"

distribution-tag:
  - main: "latest"
  - "release/*": "next"
  - "feature/*": "beta"
  - tag: "stable"

default-template: "{{ref-name}}-{{timestamp}}-{{run-number}}"
