name: Build and Publish

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Install Sonar Scanner
      run: npm install -g sonar-scanner

    - name: Build
      working-directory: maas-agent-service
      run: CGO_ENABLED=0 go build

    - name: Test with coverage
      working-directory: maas-agent-service
      run: go test -v ./... -coverprofile coverage.out

    - name: Upload coverage report to SonarCloud
      working-directory: maas-agent-service
      run: |
        sonar-scanner \
          -Dproject.settings=sonar-project.properties \
          -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }} \
          -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }} \
          -Dsonar.host.url=${{ vars.SONAR_HOST_URL }} \
          -Dsonar.go.coverage.reportPaths=coverage.out
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-build:
    uses: netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@docker_build
    with:
      dry-run: false

